project:
  type: website
  output-dir: docs
  
website:
  title: "Solutions (ISLR 1e)"
  search: true
  reader-mode: true
  repo-url: https://github.com/Aditya-Dahiya/ISLR1solutions
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - solutions.qmd
      - about.qmd
    logo: "cover-image.jpg"
    logo-alt: "Solutions: An Introduction to Statistical Learning: with Applications in R (1st Edition)"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Aditya-Dahiya/ISLR1solutions
          - text: Report a Bug
            url:  https://github.com/Aditya-Dahiya/ISLR1solutions/issues
  sidebar:
    style: "docked"
    search: true
    subtitle: "Chapters"
    contents:
      - Chapter2e.qmd
      - Chapter3e.qmd
      - Chapter3l.qmd
      - Chapter4e.qmd
      - Chapter4l.qmd
      - Chapter5e.qmd
      - Chapter5l.qmd
      - Chapter6e.qmd
format:
  html:
    theme: journal
    css: styles.css
    toc: true





